
import __ASTRO_IMAGE_IMPORT_3SG32 from "@/assets/images/AstroPaper-v5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-5.md";
import __ASTRO_IMAGE_IMPORT_Z2lKawd from "../../../assets/images/AstroPaper-v5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-5.md";
import __ASTRO_IMAGE_IMPORT_G5Mmz from "@/assets/images/AstroPaper-v4.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-4.md";
import __ASTRO_IMAGE_IMPORT_Z1Iy4cF from "../../../assets/images/AstroPaper-v4.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-4.md";
import __ASTRO_IMAGE_IMPORT_Z1kAfM8 from "@/assets/images/AstroPaper-v3.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-3.md";
import __ASTRO_IMAGE_IMPORT_2jgvgU from "@/assets/images/AstroPaper-v4.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-4.md";
import __ASTRO_IMAGE_IMPORT_1yXx3S from "../../../assets/images/AstroPaper-v4.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-4.md";
import __ASTRO_IMAGE_IMPORT_1jhSG7 from "@/assets/images/AstroPaper-v3.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-3.md";
import __ASTRO_IMAGE_IMPORT_RV8w2 from "@/assets/images/AstroPaper-v5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-5.md";
import __ASTRO_IMAGE_IMPORT_8Daj0 from "../../../assets/images/AstroPaper-v5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-5.md";
export default new Map([["@/assets/images/AstroPaper-v5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-5.md", __ASTRO_IMAGE_IMPORT_3SG32], ["../../../assets/images/AstroPaper-v5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-5.md", __ASTRO_IMAGE_IMPORT_Z2lKawd], ["@/assets/images/AstroPaper-v4.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-4.md", __ASTRO_IMAGE_IMPORT_G5Mmz], ["../../../assets/images/AstroPaper-v4.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-4.md", __ASTRO_IMAGE_IMPORT_Z1Iy4cF], ["@/assets/images/AstroPaper-v3.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-3.md", __ASTRO_IMAGE_IMPORT_Z1kAfM8], ["@/assets/images/AstroPaper-v4.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-4.md", __ASTRO_IMAGE_IMPORT_2jgvgU], ["../../../assets/images/AstroPaper-v4.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-4.md", __ASTRO_IMAGE_IMPORT_1yXx3S], ["@/assets/images/AstroPaper-v3.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fnews%2Fastro-paper-3.md", __ASTRO_IMAGE_IMPORT_1jhSG7], ["@/assets/images/AstroPaper-v5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-5.md", __ASTRO_IMAGE_IMPORT_RV8w2], ["../../../assets/images/AstroPaper-v5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Finsights%2Fastro-paper-5.md", __ASTRO_IMAGE_IMPORT_8Daj0]]);
		